name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

 deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USER }}
        password  : ${{ secrets.TEST_PWD }}
        port: ${{ secrets.TEST_PORT }}
        script: |
          cd /bin
          sudo rm -r tarantoolexperiments
          sudo git clone https://${{ secrets.GIT_PWD }}@github.com/vladzvx/tntexps
          sudo chmod u+x tarantoolexperiments
          cd tarantoolexperiments
          sudo docker-compose up -d --build
