name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

 deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.TEST_HOST }}
        username: ${{ secrets.TEST_USER }}
        password  : ${{ secrets.TEST_PWD }}
        port: ${{ secrets.TEST_PORT }}
        command_timeout: 200m
        script: |
          cd /bin
          rm -r tntexps
          git clone https://${{ secrets.GIT_PWD }}@github.com/vladzvx/tntexps
          chmod u+x tntexps
          cd tntexps
          docker-compose up -d --build
